stages:
  - test
  - report

run_automation:
  stage: test
  image: mcr.microsoft.com/playwright:v1.40.0-jammy
  script:
    - npm ci
    - npx playwright test --reporter=line,allure-playwright
  artifacts:
    when: always
    paths:
      - allure-results/

generate_allure_report:
  stage: report
  image: frankescobar/allure-docker-service
  script:
    - allure generate allure-results -o allure-report --clean
  artifacts:
    paths:
      - allure-report/
