import type {
  FullConfig,
  FullResult,
  Reporter,
  Suite,
  TestCase,
  TestResult,
} from '@playwright/test/reporter';

/**
 * Custom Playwright Reporter — Scenario OK/KO Format
 *
 * For each test (scenario), prints:
 *   ✅ OK  | Scenario: Positive login scenario        (1.2s)
 *   ❌ KO  | Scenario: Invalid password scenario      (0.8s)
 *       ↳  Error: expect(received).toHaveText(expected)
 *
 * Generated by Devoteam Smart Test Accelerator
 */

const COLORS = {
  reset: '\x1b[0m',
  bold: '\x1b[1m',
  dim: '\x1b[2m',
  green: '\x1b[32m',
  red: '\x1b[31m',
  yellow: '\x1b[33m',
  cyan: '\x1b[36m',
  gray: '\x1b[90m',
  bgGreen: '\x1b[42m',
  bgRed: '\x1b[41m',
  white: '\x1b[37m',
};

class ScenarioReporter implements Reporter {
  private passed = 0;
  private failed = 0;
  private skipped = 0;
  private startTime = 0;
  private results: { title: string; status: string; duration: number; error?: string; steps?: string[] }[] = [];

  onBegin(config: FullConfig, suite: Suite) {
    this.startTime = Date.now();
    const totalTests = suite.allTests().length;
    console.log('');
    console.log(`${COLORS.bold}${COLORS.cyan}╔══════════════════════════════════════════════════════════════╗${COLORS.reset}`);
    console.log(`${COLORS.bold}${COLORS.cyan}║${COLORS.reset}  ${COLORS.bold}🚀 Smart Test Accelerator — Playwright Execution Report${COLORS.reset}   ${COLORS.cyan}║${COLORS.reset}`);
    console.log(`${COLORS.bold}${COLORS.cyan}╠══════════════════════════════════════════════════════════════╣${COLORS.reset}`);
    console.log(`${COLORS.bold}${COLORS.cyan}║${COLORS.reset}  📋 Total scenarios: ${COLORS.bold}${totalTests}${COLORS.reset}${' '.repeat(Math.max(0, 39 - String(totalTests).length))}${COLORS.cyan}║${COLORS.reset}`);
    console.log(`${COLORS.bold}${COLORS.cyan}║${COLORS.reset}  🕐 Started at: ${COLORS.dim}${new Date().toLocaleTimeString()}${COLORS.reset}${' '.repeat(Math.max(0, 35 - new Date().toLocaleTimeString().length))}${COLORS.cyan}║${COLORS.reset}`);
    console.log(`${COLORS.bold}${COLORS.cyan}╚══════════════════════════════════════════════════════════════╝${COLORS.reset}`);
    console.log('');
  }

  onTestEnd(test: TestCase, result: TestResult) {
    const duration = result.duration / 1000;
    const durationStr = `${duration.toFixed(1)}s`;
    const title = test.title;

    // Collect step info
    const steps = result.steps
      .filter(s => s.category === 'test.step')
      .map(s => {
        const stepStatus = s.error ? '❌' : '✅';
        return `${stepStatus} ${s.title}`;
      });

    if (result.status === 'passed') {
      this.passed++;
      console.log(`  ${COLORS.bgGreen}${COLORS.white}${COLORS.bold} OK ${COLORS.reset}  ${COLORS.green}│${COLORS.reset} ${COLORS.bold}${title}${COLORS.reset} ${COLORS.dim}(${durationStr})${COLORS.reset}`);

      // Print steps for passed tests
      if (steps.length > 0) {
        steps.forEach(step => {
          console.log(`        ${COLORS.dim}↳ ${step}${COLORS.reset}`);
        });
      }

      this.results.push({ title, status: 'OK', duration: result.duration, steps });
    } else if (result.status === 'failed' || result.status === 'timedOut') {
      this.failed++;
      const statusLabel = result.status === 'timedOut' ? ' KO (TIMEOUT) ' : ' KO ';
      console.log(`  ${COLORS.bgRed}${COLORS.white}${COLORS.bold}${statusLabel}${COLORS.reset}  ${COLORS.red}│${COLORS.reset} ${COLORS.bold}${title}${COLORS.reset} ${COLORS.dim}(${durationStr})${COLORS.reset}`);

      // Print steps for failed tests
      if (steps.length > 0) {
        steps.forEach(step => {
          console.log(`        ${COLORS.dim}↳ ${step}${COLORS.reset}`);
        });
      }

      // Print error details
      if (result.errors && result.errors.length > 0) {
        for (const error of result.errors) {
          const errorMsg = error.message || error.toString();
          // Print first 3 lines of error for readability
          const lines = errorMsg.split('\n').slice(0, 3);
          lines.forEach((line: string, idx: number) => {
            const prefix = idx === 0 ? '🔴 Error' : '       ';
            console.log(`        ${COLORS.red}↳ ${prefix}: ${line.trim()}${COLORS.reset}`);
          });
        }
      }

      this.results.push({
        title,
        status: 'KO',
        duration: result.duration,
        error: result.errors?.[0]?.message?.split('\n')[0] || 'Unknown error',
        steps,
      });
    } else if (result.status === 'skipped') {
      this.skipped++;
      console.log(`  ${COLORS.yellow}${COLORS.bold} SKIP ${COLORS.reset} ${COLORS.yellow}│${COLORS.reset} ${COLORS.dim}${title}${COLORS.reset}`);
      this.results.push({ title, status: 'SKIP', duration: 0 });
    }

    console.log('');
  }

  onEnd(result: FullResult) {
    const totalDuration = ((Date.now() - this.startTime) / 1000).toFixed(1);
    const total = this.passed + this.failed + this.skipped;

    console.log(`${COLORS.bold}${COLORS.cyan}╔══════════════════════════════════════════════════════════════╗${COLORS.reset}`);
    console.log(`${COLORS.bold}${COLORS.cyan}║${COLORS.reset}  ${COLORS.bold}📊 EXECUTION SUMMARY${COLORS.reset}${' '.repeat(41)}${COLORS.cyan}║${COLORS.reset}`);
    console.log(`${COLORS.bold}${COLORS.cyan}╠══════════════════════════════════════════════════════════════╣${COLORS.reset}`);
    console.log(`${COLORS.bold}${COLORS.cyan}║${COLORS.reset}  ${COLORS.green}✅ OK :  ${this.passed}${COLORS.reset}${' '.repeat(Math.max(0, 52 - String(this.passed).length))}${COLORS.cyan}║${COLORS.reset}`);
    console.log(`${COLORS.bold}${COLORS.cyan}║${COLORS.reset}  ${COLORS.red}❌ KO :  ${this.failed}${COLORS.reset}${' '.repeat(Math.max(0, 52 - String(this.failed).length))}${COLORS.cyan}║${COLORS.reset}`);
    if (this.skipped > 0) {
      console.log(`${COLORS.bold}${COLORS.cyan}║${COLORS.reset}  ${COLORS.yellow}⏭ SKIP:  ${this.skipped}${COLORS.reset}${' '.repeat(Math.max(0, 52 - String(this.skipped).length))}${COLORS.cyan}║${COLORS.reset}`);
    }
    console.log(`${COLORS.bold}${COLORS.cyan}║${COLORS.reset}  📋 Total: ${total}  ⏱ Duration: ${totalDuration}s${' '.repeat(Math.max(0, 32 - String(total).length - totalDuration.length))}${COLORS.cyan}║${COLORS.reset}`);
    console.log(`${COLORS.bold}${COLORS.cyan}╠══════════════════════════════════════════════════════════════╣${COLORS.reset}`);

    const passRate = total > 0 ? ((this.passed / total) * 100).toFixed(1) : '0.0';
    const statusEmoji = this.failed === 0 ? '🎉' : '⚠️';
    const statusText = this.failed === 0 ? 'ALL SCENARIOS PASSED' : `${this.failed} SCENARIO(S) FAILED`;
    console.log(`${COLORS.bold}${COLORS.cyan}║${COLORS.reset}  ${statusEmoji} ${COLORS.bold}${this.failed === 0 ? COLORS.green : COLORS.red}${statusText}${COLORS.reset} — Pass rate: ${COLORS.bold}${passRate}%${COLORS.reset}${' '.repeat(Math.max(0, 14 - statusText.length - passRate.length))}${COLORS.cyan}║${COLORS.reset}`);
    console.log(`${COLORS.bold}${COLORS.cyan}╚══════════════════════════════════════════════════════════════╝${COLORS.reset}`);
    console.log('');
  }
}

export default ScenarioReporter;
