"""
Moteur de Scaffolding — Génération automatique de projets Playwright/TypeScript.

Prend des scénarios Gherkin validés et génère physiquement sur le disque
une arborescence de projet complète avec Page Objects (POM) et fichiers
.spec.ts conformes aux normes TypeScript.

Auteur  : Mounira Ismail
Date    : Juin 2026
"""

import os
import re
import json
import shutil
from datetime import datetime
from typing import Any, Optional


# ── Templates ────────────────────────────────────────────────────────────

PACKAGE_JSON_TEMPLATE = """{
  "name": "%(project_name)s",
  "version": "1.0.0",
  "description": "%(description)s",
  "scripts": {
    "test": "npx playwright test",
    "test:headed": "npx playwright test --headed",
    "test:ui": "npx playwright test --ui",
    "show-report": "npx playwright show-report"
  },
  "devDependencies": {
    "@playwright/test": "^1.44.0",
    "typescript": "^5.4.0"
  }
}
"""

TSCONFIG_TEMPLATE = """{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "outDir": "./dist",
    "rootDir": "."
  },
  "include": ["tests/**/*.ts", "pages/**/*.ts"],
  "exclude": ["node_modules"]
}
"""

PLAYWRIGHT_CONFIG_TEMPLATE = """import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './tests',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: [
    ['./scenario-reporter.ts'],
    ['html'],
  ],
  use: {
    baseURL: '%(base_url)s',
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],
});
"""

GITIGNORE_TEMPLATE = """node_modules/
dist/
test-results/
playwright-report/
blob-report/
.env
"""

GITLAB_CI_TEMPLATE = """stages:
  - test
  - report

run_automation:
  stage: test
  image: mcr.microsoft.com/playwright:v1.44.0-jammy
  script:
    - npm ci
    - npx playwright install --with-deps
    - npx playwright test --reporter=line,html
  artifacts:
    when: always
    paths:
      - playwright-report/
      - test-results/
"""

README_TEMPLATE = """# %(project_name)s

> Auto-generated Playwright/TypeScript test suite by **Devoteam Smart Test Accelerator**

## Structure

```
%(tree)s
```

## Quick Start

```bash
npm install
npx playwright install
npx playwright test
```

## Generated on

%(timestamp)s
"""


# ── Page Object Template ─────────────────────────────────────────────────

PAGE_OBJECT_TEMPLATE = """import { Page, Locator } from '@playwright/test';

/**
 * Page Object Model for %(page_name)s.
 * Auto-generated by Devoteam Smart Test Accelerator.
 */
export class %(class_name)s {
  readonly page: Page;
%(locator_declarations)s

  constructor(page: Page) {
    this.page = page;
%(locator_assignments)s
  }

%(methods)s}
"""

SPEC_FILE_TEMPLATE = """import { test, expect } from '@playwright/test';
%(page_imports)s

test.describe('%(feature_title)s', () => {
%(page_instances)s

  test.beforeEach(async ({ page }) => {
%(page_constructors)s
  });

%(test_blocks)s
});
"""

FEATURE_FILE_TEMPLATE = """%(gherkin_content)s
"""

SCENARIO_REPORTER_TEMPLATE = """import type {
  FullConfig,
  FullResult,
  Reporter,
  Suite,
  TestCase,
  TestResult,
} from '@playwright/test/reporter';

/**
 * Custom Playwright Reporter — Scenario OK/KO Format
 *
 * For each test (scenario), prints:
 *   ✅ OK  | Scenario: Positive login scenario        (1.2s)
 *   ❌ KO  | Scenario: Invalid password scenario      (0.8s)
 *       ↳  Error: expect(received).toHaveText(expected)
 *
 * Generated by Devoteam Smart Test Accelerator
 */

const COLORS = {
  reset: '\\x1b[0m',
  bold: '\\x1b[1m',
  dim: '\\x1b[2m',
  green: '\\x1b[32m',
  red: '\\x1b[31m',
  yellow: '\\x1b[33m',
  cyan: '\\x1b[36m',
  gray: '\\x1b[90m',
  bgGreen: '\\x1b[42m',
  bgRed: '\\x1b[41m',
  white: '\\x1b[37m',
};

class ScenarioReporter implements Reporter {
  private passed = 0;
  private failed = 0;
  private skipped = 0;
  private startTime = 0;

  onBegin(config: FullConfig, suite: Suite) {
    this.startTime = Date.now();
    const totalTests = suite.allTests().length;
    console.log('');
    console.log(`${COLORS.bold}${COLORS.cyan}══════════════════════════════════════════════════════${COLORS.reset}`);
    console.log(`  🚀 ${COLORS.bold}Smart Test Accelerator — Execution Report${COLORS.reset}`);
    console.log(`  📋 Total scenarios: ${COLORS.bold}${totalTests}${COLORS.reset}`);
    console.log(`${COLORS.bold}${COLORS.cyan}══════════════════════════════════════════════════════${COLORS.reset}`);
    console.log('');
  }

  onTestEnd(test: TestCase, result: TestResult) {
    const duration = result.duration / 1000;
    const durationStr = `${duration.toFixed(1)}s`;
    const title = test.title;

    const steps = result.steps
      .filter(s => s.category === 'test.step')
      .map(s => {
        const stepStatus = s.error ? '❌' : '✅';
        return `${stepStatus} ${s.title}`;
      });

    if (result.status === 'passed') {
      this.passed++;
      console.log(`  ${COLORS.bgGreen}${COLORS.white}${COLORS.bold} OK ${COLORS.reset}  ${COLORS.green}│${COLORS.reset} ${COLORS.bold}${title}${COLORS.reset} ${COLORS.dim}(${durationStr})${COLORS.reset}`);
      if (steps.length > 0) {
        steps.forEach(step => {
          console.log(`        ${COLORS.dim}↳ ${step}${COLORS.reset}`);
        });
      }
    } else if (result.status === 'failed' || result.status === 'timedOut') {
      this.failed++;
      const statusLabel = result.status === 'timedOut' ? ' KO (TIMEOUT) ' : ' KO ';
      console.log(`  ${COLORS.bgRed}${COLORS.white}${COLORS.bold}${statusLabel}${COLORS.reset}  ${COLORS.red}│${COLORS.reset} ${COLORS.bold}${title}${COLORS.reset} ${COLORS.dim}(${durationStr})${COLORS.reset}`);
      if (steps.length > 0) {
        steps.forEach(step => {
          console.log(`        ${COLORS.dim}↳ ${step}${COLORS.reset}`);
        });
      }
      if (result.errors && result.errors.length > 0) {
        for (const error of result.errors) {
          const errorMsg = error.message || error.toString();
          const lines = errorMsg.split('\\n').slice(0, 3);
          lines.forEach((line: string, idx: number) => {
            const prefix = idx === 0 ? '🔴 Error' : '       ';
            console.log(`        ${COLORS.red}↳ ${prefix}: ${line.trim()}${COLORS.reset}`);
          });
        }
      }
    } else if (result.status === 'skipped') {
      this.skipped++;
      console.log(`  ${COLORS.yellow}${COLORS.bold} SKIP ${COLORS.reset} ${COLORS.yellow}│${COLORS.reset} ${COLORS.dim}${title}${COLORS.reset}`);
    }
    console.log('');
  }

  onEnd(result: FullResult) {
    const totalDuration = ((Date.now() - this.startTime) / 1000).toFixed(1);
    const total = this.passed + this.failed + this.skipped;
    const passRate = total > 0 ? ((this.passed / total) * 100).toFixed(1) : '0.0';
    const statusEmoji = this.failed === 0 ? '🎉' : '⚠️';
    const statusText = this.failed === 0 ? 'ALL SCENARIOS PASSED' : `${this.failed} SCENARIO(S) FAILED`;

    console.log(`${COLORS.bold}${COLORS.cyan}══════════════════════════════════════════════════════${COLORS.reset}`);
    console.log(`  📊 ${COLORS.bold}EXECUTION SUMMARY${COLORS.reset}`);
    console.log(`  ${COLORS.green}✅ OK :  ${this.passed}${COLORS.reset}`);
    console.log(`  ${COLORS.red}❌ KO :  ${this.failed}${COLORS.reset}`);
    if (this.skipped > 0) {
      console.log(`  ${COLORS.yellow}⏭ SKIP:  ${this.skipped}${COLORS.reset}`);
    }
    console.log(`  📋 Total: ${total}  ⏱ Duration: ${totalDuration}s`);
    console.log(`  ${statusEmoji} ${COLORS.bold}${this.failed === 0 ? COLORS.green : COLORS.red}${statusText}${COLORS.reset} — Pass rate: ${COLORS.bold}${passRate}%${COLORS.reset}`);
    console.log(`${COLORS.bold}${COLORS.cyan}══════════════════════════════════════════════════════${COLORS.reset}`);
    console.log('');
  }
}

export default ScenarioReporter;
"""


# ── Helper Utilities ─────────────────────────────────────────────────────

def _sanitize_filename(name: str) -> str:
    """Convert a title into a safe filename (kebab-case)."""
    name = re.sub(r"[^a-zA-Z0-9\s_-]", "", name)
    name = re.sub(r"\s+", "-", name.strip())
    return name.lower()


def _to_pascal_case(text: str) -> str:
    """Convert text to PascalCase for class names."""
    words = re.split(r"[\s_\-]+", text)
    return "".join(w.capitalize() for w in words if w)


def _to_camel_case(text: str) -> str:
    """Convert text to camelCase for variable names."""
    # Split on separators first, then on uppercase boundaries for PascalCase input
    if re.search(r"[\s_\-]", text):
        pascal = _to_pascal_case(text)
    else:
        # Already PascalCase — split on uppercase boundaries
        words = re.sub(r'([A-Z])', r' \1', text).split()
        pascal = "".join(w.capitalize() for w in words if w)
    return pascal[0].lower() + pascal[1:] if pascal else ""


def _indent(text: str, spaces: int = 2) -> str:
    """Indent each line of text."""
    prefix = " " * spaces
    return "\n".join(prefix + line if line.strip() else line for line in text.split("\n"))


def _build_tree_string(root_path: str, prefix: str = "") -> str:
    """Build a simple tree representation of a directory."""
    lines = []
    try:
        entries = sorted(os.listdir(root_path))
    except OSError:
        return ""
    entries = [e for e in entries if e not in ("node_modules", ".git", "__pycache__", "dist")]
    for i, entry in enumerate(entries):
        connector = "└── " if i == len(entries) - 1 else "├── "
        full_path = os.path.join(root_path, entry)
        lines.append(f"{prefix}{connector}{entry}")
        if os.path.isdir(full_path):
            extension = "    " if i == len(entries) - 1 else "│   "
            lines.append(_build_tree_string(full_path, prefix + extension))
    return "\n".join(line for line in lines if line)


# ── Core Scaffolder ──────────────────────────────────────────────────────

class ScaffoldResult:
    """Result of a scaffold operation."""

    def __init__(self, output_dir: str):
        self.output_dir = output_dir
        self.created_files: list[str] = []
        self.created_dirs: list[str] = []
        self.errors: list[str] = []

    @property
    def success(self) -> bool:
        return len(self.errors) == 0

    def to_dict(self) -> dict[str, Any]:
        return {
            "success": self.success,
            "output_dir": self.output_dir,
            "created_files": self.created_files,
            "created_dirs": self.created_dirs,
            "errors": self.errors,
            "file_count": len(self.created_files),
            "dir_count": len(self.created_dirs),
        }


class ProjectScaffolder:
    """
    Generates a complete Playwright/TypeScript project on disk from
    Gherkin scenarios and AI-generated code.

    The generated project follows the POM pattern:
        project-name/
        ├── pages/            # Page Object classes
        ├── tests/            # .spec.ts test files
        ├── features/         # .feature Gherkin files
        ├── package.json
        ├── tsconfig.json
        ├── playwright.config.ts
        ├── .gitignore
        └── .gitlab-ci.yml
    """

    def __init__(self, output_base: str = None):
        """
        Args:
            output_base: Root directory where projects are generated.
                         Defaults to <workspace>/generated-projects/
        """
        if output_base is None:
            output_base = os.path.join(
                os.path.dirname(os.path.dirname(__file__)),
                "generated-projects"
            )
        self.output_base = os.path.abspath(output_base)

    # ── Public API ───────────────────────────────────────────────────

    def scaffold_project(
        self,
        project_name: str,
        gherkin_content: str,
        page_objects: list[dict[str, str]],
        spec_files: list[dict[str, str]],
        base_url: str = "http://localhost:3000",
        include_ci: bool = True,
        overwrite: bool = False,
    ) -> ScaffoldResult:
        """
        Generate a complete Playwright/TypeScript project on disk.

        Args:
            project_name: Name of the project (used for directory + package.json).
            gherkin_content: Raw Gherkin .feature content.
            page_objects: List of {"filename": "LoginPage.ts", "code": "..."}.
            spec_files: List of {"filename": "login.spec.ts", "code": "..."}.
            base_url: Target application URL for playwright.config.ts.
            include_ci: Whether to include .gitlab-ci.yml.
            overwrite: If True, removes existing project dir first.

        Returns:
            ScaffoldResult with created files/dirs and any errors.
        """
        safe_name = _sanitize_filename(project_name)
        project_dir = os.path.join(self.output_base, safe_name)
        result = ScaffoldResult(project_dir)

        # Handle existing directory
        if os.path.exists(project_dir):
            if overwrite:
                shutil.rmtree(project_dir)
            else:
                result.errors.append(
                    f"Directory already exists: {project_dir}. "
                    f"Use overwrite=True to replace."
                )
                return result

        try:
            # Create directory structure
            dirs = ["pages", "tests", "features"]
            for d in dirs:
                dir_path = os.path.join(project_dir, d)
                os.makedirs(dir_path, exist_ok=True)
                result.created_dirs.append(d)

            # Write config files
            self._write_file(
                project_dir, "package.json",
                PACKAGE_JSON_TEMPLATE % {
                    "project_name": safe_name,
                    "description": f"Auto-generated test suite for {project_name}",
                },
                result,
            )

            self._write_file(
                project_dir, "tsconfig.json",
                TSCONFIG_TEMPLATE,
                result,
            )

            self._write_file(
                project_dir, "playwright.config.ts",
                PLAYWRIGHT_CONFIG_TEMPLATE % {"base_url": base_url},
                result,
            )

            self._write_file(project_dir, ".gitignore", GITIGNORE_TEMPLATE, result)

            # Write custom scenario reporter
            self._write_file(
                project_dir, "scenario-reporter.ts",
                SCENARIO_REPORTER_TEMPLATE,
                result,
            )

            if include_ci:
                self._write_file(project_dir, ".gitlab-ci.yml", GITLAB_CI_TEMPLATE, result)

            # Write Gherkin feature file
            feature_filename = f"{safe_name}.feature"
            self._write_file(
                os.path.join(project_dir, "features"),
                feature_filename,
                gherkin_content,
                result,
            )

            # Write Page Objects
            for po in page_objects:
                filename = po.get("filename", "UnknownPage.ts")
                if not filename.endswith(".ts"):
                    filename += ".ts"
                self._write_file(
                    os.path.join(project_dir, "pages"),
                    filename,
                    po["code"],
                    result,
                )

            # Write Spec files
            for spec in spec_files:
                filename = spec.get("filename", "test.spec.ts")
                if not filename.endswith(".ts"):
                    filename += ".ts"
                self._write_file(
                    os.path.join(project_dir, "tests"),
                    filename,
                    spec["code"],
                    result,
                )

            # Write README
            tree = _build_tree_string(project_dir)
            self._write_file(
                project_dir, "README.md",
                README_TEMPLATE % {
                    "project_name": project_name,
                    "tree": tree,
                    "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M UTC"),
                },
                result,
            )

        except OSError as e:
            result.errors.append(f"Filesystem error: {e}")

        return result

    def scaffold_from_gherkin_json(
        self,
        project_name: str,
        gherkin_json: dict[str, Any],
        base_url: str = "http://localhost:3000",
        include_ci: bool = True,
        overwrite: bool = False,
    ) -> ScaffoldResult:
        """
        Generate a project from structured Gherkin JSON (as produced by
        the AI service's generate_gherkin_json()).

        Deterministically generates Page Objects and spec files from the
        structured JSON without calling the AI — pure template-based.

        Args:
            gherkin_json: Structured JSON with feature_title, scenarios, steps.
        """
        # Import converter
        import sys
        core_dir = os.path.dirname(__file__)
        if core_dir not in sys.path:
            sys.path.insert(0, core_dir)
        from gherkin_validator import json_to_gherkin

        # Convert JSON to raw Gherkin
        gherkin_text = json_to_gherkin(gherkin_json)

        # Generate deterministic Page Objects from scenario steps
        page_objects = self._generate_page_objects_from_json(gherkin_json)

        # Generate spec files from scenarios
        spec_files = self._generate_spec_files_from_json(gherkin_json, page_objects)

        return self.scaffold_project(
            project_name=project_name,
            gherkin_content=gherkin_text,
            page_objects=page_objects,
            spec_files=spec_files,
            base_url=base_url,
            include_ci=include_ci,
            overwrite=overwrite,
        )

    # ── Deterministic Code Generators ────────────────────────────────

    def _generate_page_objects_from_json(
        self, gherkin_json: dict[str, Any]
    ) -> list[dict[str, str]]:
        """
        Analyze Gherkin JSON scenarios and generate Page Object classes.
        
        Extracts page context from step text to determine which pages
        are involved and what locators/actions they need.
        """
        feature_title = gherkin_json.get("feature_title", "App")
        scenarios = gherkin_json.get("scenarios", [])

        # Detect pages from step text patterns
        pages = self._detect_pages(scenarios, feature_title)

        result = []
        for page_name, page_data in pages.items():
            class_name = _to_pascal_case(page_name) + "Page"
            filename = f"{class_name}.ts"

            # Build locator declarations
            locator_lines = []
            assignment_lines = []
            for loc_name, loc_selector in page_data["locators"].items():
                locator_lines.append(f"  readonly {loc_name}: Locator;")
                assignment_lines.append(
                    f"    this.{loc_name} = page.locator('{loc_selector}');"
                )

            # Build methods
            method_blocks = []
            for method_name, method_body in page_data["methods"].items():
                method_blocks.append(method_body)

            code = PAGE_OBJECT_TEMPLATE % {
                "page_name": page_name,
                "class_name": class_name,
                "locator_declarations": "\n".join(locator_lines),
                "locator_assignments": "\n".join(assignment_lines),
                "methods": "\n".join(method_blocks),
            }

            result.append({"filename": filename, "code": code.strip() + "\n"})

        return result

    def _generate_spec_files_from_json(
        self,
        gherkin_json: dict[str, Any],
        page_objects: list[dict[str, str]],
    ) -> list[dict[str, str]]:
        """Generate .spec.ts files from Gherkin JSON scenarios."""
        feature_title = gherkin_json.get("feature_title", "Test Suite")
        scenarios = gherkin_json.get("scenarios", [])
        safe_name = _sanitize_filename(feature_title)

        # Collect page class names for imports
        page_classes = []
        for po in page_objects:
            match = re.search(r"export class (\w+)", po["code"])
            if match:
                page_classes.append(match.group(1))

        # Build imports
        import_lines = []
        for cls in page_classes:
            import_lines.append(
                f"import {{ {cls} }} from '../pages/{cls}';"
            )
        page_imports = "\n".join(import_lines)

        # Build instance declarations
        var_lines = []
        constructor_lines = []
        for cls in page_classes:
            var_name = _to_camel_case(cls)
            var_lines.append(f"  let {var_name}: {cls};")
            constructor_lines.append(f"    {var_name} = new {cls}(page);")

        page_instances = "\n".join(var_lines)
        page_constructors = "\n".join(constructor_lines)

        # Build test blocks
        test_blocks = []
        for scenario in scenarios:
            title = scenario.get("title", "Unnamed Scenario")
            steps = scenario.get("steps", [])

            step_blocks = []
            for step in steps:
                keyword = step.get("keyword", "Given")
                text = step.get("text", "")
                step_label = f"{keyword} {text}"
                # Escape quotes in the step label
                step_label_escaped = step_label.replace("'", "\\'")

                step_blocks.append(
                    f"    await test.step('{step_label_escaped}', async () => {{\n"
                    f"      // TODO: Implement step logic\n"
                    f"    }});\n"
                )

            test_body = "\n".join(step_blocks)
            test_block = (
                f"  test('{title}', async () => {{\n"
                f"{test_body}"
                f"  }});\n"
            )
            test_blocks.append(test_block)

        all_tests = "\n".join(test_blocks)

        code = SPEC_FILE_TEMPLATE % {
            "feature_title": feature_title,
            "page_imports": page_imports,
            "page_instances": page_instances,
            "page_constructors": page_constructors,
            "test_blocks": all_tests,
        }

        return [{"filename": f"{safe_name}.spec.ts", "code": code.strip() + "\n"}]

    def _detect_pages(
        self, scenarios: list[dict], feature_title: str
    ) -> dict[str, dict]:
        """
        Analyze Gherkin steps to detect which pages are involved and
        what locators/methods they likely need.

        Uses pattern matching on step text to infer page context.
        """
        pages: dict[str, dict] = {}

        # Common page patterns in step text
        page_patterns = [
            (r"(?:is on|visits?|navigates? to|opens?)\s+(?:the\s+)?(.+?)\s+page",
             "navigate"),
            (r"(?:is on|visits?)\s+(?:the\s+)?(.+?)$", "navigate"),
        ]

        # Common action patterns
        action_patterns = [
            (r"enters?\s+(?:the\s+)?(?:a\s+)?(\w+)\s+\"(.+?)\"", "input"),
            (r"enters?\s+(?:the\s+)?(?:a\s+)?(\w+)", "input"),
            (r"clicks?\s+(?:the\s+)?\"(.+?)\"", "button"),
            (r"clicks?\s+(?:the\s+)?(.+?)\s+button", "button"),
            (r"(?:sees?|views?|displays?)\s+(?:the\s+)?(.+?)$", "element"),
            (r"(?:is\s+)?redirected\s+to\s+(?:the\s+)?(.+?)$", "navigation"),
            (r"error\s+(?:message\s+)?\"(.+?)\"", "error"),
        ]

        # Use feature title as default page name
        default_page = re.sub(r"\s+", "", feature_title.split("-")[0].split("–")[0].strip())
        if default_page not in pages:
            pages[default_page] = {
                "locators": {},
                "methods": {
                    "navigate": (
                        "  async navigate(): Promise<void> {\n"
                        "    await this.page.goto('/');\n"
                        "  }\n"
                    ),
                },
            }

        # Scan all steps
        for scenario in scenarios:
            for step in scenario.get("steps", []):
                text = step.get("text", "")

                # Detect page references
                for pattern, action_type in page_patterns:
                    match = re.search(pattern, text, re.IGNORECASE)
                    if match:
                        page_name = _to_pascal_case(match.group(1).strip())
                        if page_name not in pages:
                            pages[page_name] = {
                                "locators": {},
                                "methods": {
                                    "navigate": (
                                        "  async navigate(): Promise<void> {\n"
                                        "    await this.page.goto('/');\n"
                                        "  }\n"
                                    ),
                                },
                            }

                # Detect input fields
                for pattern, action_type in action_patterns:
                    match = re.search(pattern, text, re.IGNORECASE)
                    if match:
                        current_page = list(pages.keys())[0]
                        if action_type == "input":
                            field_name = _to_camel_case(match.group(1)) + "Input"
                            selector = f'[data-testid="{_sanitize_filename(match.group(1))}"]'
                            pages[current_page]["locators"][field_name] = selector
                        elif action_type == "button":
                            btn_text = match.group(1).strip()
                            btn_name = _to_camel_case(btn_text) + "Button"
                            selector = f"button:has-text('{btn_text}')"
                            pages[current_page]["locators"][btn_name] = selector
                        elif action_type == "error":
                            pages[current_page]["locators"]["errorMessage"] = (
                                '[role="alert"], .error-message, [data-testid="error"]'
                            )

        return pages

    # ── File I/O ─────────────────────────────────────────────────────

    def _write_file(
        self, directory: str, filename: str, content: str, result: ScaffoldResult
    ):
        """Write a file to disk and record it in the result."""
        filepath = os.path.join(directory, filename)
        os.makedirs(os.path.dirname(filepath), exist_ok=True)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)
        rel_path = os.path.relpath(filepath, result.output_dir)
        result.created_files.append(rel_path)
