import os
import httpx
import subprocess
import tempfile
import shutil
from fastapi import HTTPException
import asyncio

async def generate_playwright_project(github_token: str, project_name: str, visibility: str = "private") -> str:
    """
    Creates a GitHub repository and pushes a Playwright scaffold to it.
    Returns the GitHub repository URL.
    """
    if not github_token:
        raise HTTPException(status_code=400, detail="GITHUB_TOKEN is not configured in the environment.")

    headers = {
        "Authorization": f"token {github_token}",
        "Accept": "application/vnd.github.v3+json"
    }

    # 1. Create GitHub Repo
    async with httpx.AsyncClient() as client:
        # Check user
        user_res = await client.get("https://api.github.com/user", headers=headers)
        if user_res.status_code != 200:
            raise HTTPException(status_code=401, detail="Invalid GITHUB_TOKEN.")
        
        user_data = user_res.json()
        username = user_data.get("login")

        # Create repo
        repo_data = {
            "name": project_name,
            "private": (visibility == "private"),
            "auto_init": False
        }
        create_res = await client.post("https://api.github.com/user/repos", headers=headers, json=repo_data)
        if create_res.status_code not in (201, 422):
            raise HTTPException(status_code=create_res.status_code, detail=f"Failed to create repo: {create_res.text}")
        
        repo_url = f"https://github.com/{username}/{project_name}"
        clone_url = f"https://{username}:{github_token}@github.com/{username}/{project_name}.git"

    # 2. Scaffold and Push via Git
    # We use a temporary directory to initialize the project
    temp_dir = tempfile.mkdtemp()
    try:
        # package.json
        package_json = """{
  "name": "%s",
  "version": "1.0.0",
  "description": "Automated tests generated by Devoteam TestGenAI",
  "scripts": {
    "test": "npx playwright test",
    "report": "npx allure serve allure-results"
  },
  "devDependencies": {
    "@playwright/test": "^1.44.0",
    "@types/node": "^20.0.0",
    "allure-playwright": "^3.0.0"
  }
}""" % project_name

        # playwright.config.ts
        playwright_config = """import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './tests',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: [
    ['html'],
    ['allure-playwright', { detail: true, outputFolder: 'allure-results', suiteTitle: false }]
  ],
  use: {
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],
});
"""
        
        # tests/demo.spec.ts
        demo_spec = """import { test, expect } from '@playwright/test';

test('has title', async ({ page }) => {
  await page.goto('https://www.google.com/');
  // Expect a title "to contain" a substring.
  await expect(page).toHaveTitle(/Google/);
});
"""

        # .github/workflows/main.yml
        github_workflow = """name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - name: Upload Allure results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: allure-results/
        retention-days: 30
    - name: Generate Allure Report
      if: always()
      run: npx allure generate allure-results --clean -o allure-report
    - name: Deploy to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
    - name: Notify TestGenAI Webhook
      if: always()
      run: |
        curl -X POST %s/api/webhooks/github/execution-result \
        -H "Content-Type: application/json" \
        -d '{"repository": "${{ github.repository }}", "status": "${{ job.status }}"}'
""" % os.environ.get("PLATFORM_URL", "http://localhost:8000")

        # gitignore
        gitignore = """node_modules/
test-results/
playwright-report/
playwright/.cache/
allure-results/
allure-report/
.env
"""

        # Write files
        os.makedirs(os.path.join(temp_dir, "tests"), exist_ok=True)
        os.makedirs(os.path.join(temp_dir, ".github", "workflows"), exist_ok=True)

        with open(os.path.join(temp_dir, "package.json"), "w") as f:
            f.write(package_json)
        with open(os.path.join(temp_dir, "playwright.config.ts"), "w") as f:
            f.write(playwright_config)
        with open(os.path.join(temp_dir, "tests", "demo.spec.ts"), "w") as f:
            f.write(demo_spec)
        with open(os.path.join(temp_dir, ".github", "workflows", "main.yml"), "w") as f:
            f.write(github_workflow)
        with open(os.path.join(temp_dir, ".gitignore"), "w") as f:
            f.write(gitignore)
        with open(os.path.join(temp_dir, "README.md"), "w") as f:
            f.write(f"# {project_name}\n\nGenerated by Devoteam TestGenAI.")

        # Execute git commands
        cmds = [
            ["git", "init"],
            ["git", "checkout", "-b", "main"],
            ["git", "add", "."],
            ["git", "config", "user.email", "testgenai@devoteam.com"],
            ["git", "config", "user.name", "TestGenAI Bot"],
            ["git", "commit", "-m", "chore: initial Playwright setup with Allure and Actions"],
            ["git", "remote", "add", "origin", clone_url],
            ["git", "push", "-u", "origin", "main", "--force"]
        ]

        for cmd in cmds:
            subprocess.run(cmd, cwd=temp_dir, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to push to GitHub: {str(e)}")
    finally:
        shutil.rmtree(temp_dir, ignore_errors=True)

    return repo_url
